# Generated by Django 3.2.8 on 2021-10-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0002_auto_20211027_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='Qrtxt',
            new_name='qrtxt',
        ),
    ]
